### ISSUE TITLE
Add option to error turtle

### ISSUE THREAD

**Issue by crazyvinvin** [MC-Synergy/MCSTurtleTracker#13]
when sending an emergency, often you don't want the turtle/computer to keep on going after that (because it's an emergency and something is probably very wrong.)

Add an optional paramater that lets us error() the turtle (with the same message) after sending an emergency message to mcst.

**Comment by Josian2004** [comment]
@crazyvinvin You don't need to manually send an error message, if you let your turtle crash by doing error(errormsg) it will automatically send an error message to MCST. Is this sufficient?

**Comment by crazyvinvin** [comment]
Oh, that works too!
