### ISSUE TITLE
Option to print status updates (and logs)

### ISSUE THREAD

**Issue by crazyvinvin** [MC-Synergy/MCSTurtleTracker#17]
Id like an option to print the statusupdates that are sent in the terminal. Maybe also printing the debug/info/warning/emergency logs. You could add some sort of config for printing logs for example (in a table).

**Comment by Josian2004** [comment]
Added in the last library update, a fourth parameter has been added in the init function to enable/disable this. 
Every time a message is sent or the status is changed, it will be printed to the turtle.

I haven't tested it yet but it should work, if it doesn't just shout at me and reopen this issue.
