### ISSUE TITLE
Network configuration changes

### ISSUE THREAD

**Issue by crazyvinvin** [MC-Synergy/MCSTurtleTracker#4]
We have been reconfiguring all the servers and domain names, and we need some small changes at your side.

please make the turtle tracker api accessible through whateveryouwant.josian.nl or whateveryouwant.josian.nl/turtletracker.

Also we have linked turtletracker.mcsynergy.nl to mcst.josian.nl. But accessing it gives a 404, this is most likely on your side.

**Comment by Josian2004** [comment]
Url of API has been changed to api.mcst.josian.nl (websocket: api.mcst.josian.nl/ws) and turtletracker.mcsynergy.nl has been added to my nginx config and is now rerouted properly

**Comment by crazyvinvin** [comment]
Routing is now: 
CNAME dns record: turtletracker.mcsynergy.nl --> mcst.josian.nl
NGINX: api.mcsynergy.nl/turtletracker/whatever --> api.mcst.josian.nl/whatever
